//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找已本地化的字符串等等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 Visual Studio 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Print {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Print() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Print", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找重写当前线程的 CurrentUICulture 
        /// 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Advance Payment Tax 的本地化字符串。
        /// </summary>
        internal static string Invoice_AdvancePaymentTax {
            get {
                return ResourceManager.GetString("Invoice_AdvancePaymentTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To be paid to the Tax agency in behalf of {0} 的本地化字符串。
        /// </summary>
        internal static string Invoice_AdvancePTComment {
            get {
                return ResourceManager.GetString("Invoice_AdvancePTComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Company Number 的本地化字符串。
        /// </summary>
        internal static string Invoice_CompanyNumber {
            get {
                return ResourceManager.GetString("Invoice_CompanyNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Email 的本地化字符串。
        /// </summary>
        internal static string Invoice_Email {
            get {
                return ResourceManager.GetString("Invoice_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Item 的本地化字符串。
        /// </summary>
        internal static string Invoice_Item {
            get {
                return ResourceManager.GetString("Invoice_Item", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Invoice number {1}# {0} # 的本地化字符串。
        /// </summary>
        internal static string Invoice_Number {
            get {
                return ResourceManager.GetString("Invoice_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Bank wire 的本地化字符串。
        /// </summary>
        internal static string Invoice_PaymentDetails {
            get {
                return ResourceManager.GetString("Invoice_PaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment details 的本地化字符串。
        /// </summary>
        internal static string Invoice_PaymentDetailsTitle {
            get {
                return ResourceManager.GetString("Invoice_PaymentDetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Phone 的本地化字符串。
        /// </summary>
        internal static string Invoice_Phone {
            get {
                return ResourceManager.GetString("Invoice_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Price 的本地化字符串。
        /// </summary>
        internal static string Invoice_Price {
            get {
                return ResourceManager.GetString("Invoice_Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Qty 的本地化字符串。
        /// </summary>
        internal static string Invoice_Qty {
            get {
                return ResourceManager.GetString("Invoice_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Service 的本地化字符串。
        /// </summary>
        internal static string Invoice_Service {
            get {
                return ResourceManager.GetString("Invoice_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SubTotal 的本地化字符串。
        /// </summary>
        internal static string Invoice_SubTotal {
            get {
                return ResourceManager.GetString("Invoice_SubTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 To 的本地化字符串。
        /// </summary>
        internal static string Invoice_To {
            get {
                return ResourceManager.GetString("Invoice_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        internal static string Invoice_Total {
            get {
                return ResourceManager.GetString("Invoice_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total to Pay 的本地化字符串。
        /// </summary>
        internal static string Invoice_TotalToPay {
            get {
                return ResourceManager.GetString("Invoice_TotalToPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VAT 的本地化字符串。
        /// </summary>
        internal static string Invoice_VAT {
            get {
                return ResourceManager.GetString("Invoice_VAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proposal 的本地化字符串。
        /// </summary>
        internal static string Proposal {
            get {
                return ResourceManager.GetString("Proposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Proposal Details 的本地化字符串。
        /// </summary>
        internal static string ProposalDetails {
            get {
                return ResourceManager.GetString("ProposalDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Total 的本地化字符串。
        /// </summary>
        internal static string Proposal_Total {
            get {
                return ResourceManager.GetString("Proposal_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Quote 的本地化字符串。
        /// </summary>
        internal static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VAT is not included 的本地化字符串。
        /// </summary>
        internal static string VAT_Not_Included {
            get {
                return ResourceManager.GetString("VAT_Not_Included", resourceCulture);
            }
        }
    }
}
